const $=id=>document.getElementById(id);
const field=$('field'), qbar=$('qbar'), f=field.getContext('2d'), q=qbar.getContext('2d');
const ui={mode:$('mode'),modeInfo:$('modeInfo'),fieldViews:$('fieldViews'),mu0:$('mu0'),tau:$('tau'),s0:$('s0'),ssd:$('ssd'),mu0v:$('mu0v'),tauv:$('tauv'),s0v:$('s0v'),ssdv:$('ssdv'),undo:$('undo'),reset:$('reset'),obs:$('obs'),modeMs:$('modeMs'),refMs:$('refMs'),posteriorKl:$('posteriorKl'),predictiveKl:$('predictiveKl'),qbarHint:$('qbarHint')};
const TAU=2*Math.PI,L2PI=Math.log(TAU),C={u0:-6,u1:6,s0:-3,s1:2,nx:180,ny:140,x0:-6,x1:6,qbins:560,mbins:220},G=C.nx*C.ny,M={l:52,r:18,t:20,b:38};
const st={xs:[],n:0,sx:0,sx2:0,view:'selected',sel:null,selW:null,exactPred:null,dist:null,exactGrid:null,pkl:null,xkl:null,refMs:null,timer:null,ver:0};
const U=new Float64Array(G),S=new Float64Array(G),V=new Float64Array(G),IV=new Float64Array(G),P0=new Float64Array(G),LL=new Float64Array(G);
for(let j=0;j<C.ny;j++){const s=C.s1-(j+.5)*(C.s1-C.s0)/C.ny,v=Math.exp(s);for(let i=0;i<C.nx;i++){const k=j*C.nx+i;U[k]=C.u0+(i+.5)*(C.u1-C.u0)/C.nx;S[k]=s;V[k]=v;IV[k]=1/v}}
const off=document.createElement('canvas');off.width=C.nx;off.height=C.ny;const of=off.getContext('2d'),img=of.createImageData(C.nx,C.ny);
const pars=()=>({m:+ui.mu0.value,t:+ui.tau.value,s:+ui.s0.value,d:+ui.ssd.value});
const ln=(x,m,d)=>{const z=(x-m)/d;return-Math.log(d)-.5*L2PI-.5*z*z};
function common(){const {m,t,s,d}=pars(),has=st.n>0,last=has?st.xs[st.n-1]:0;for(let k=0;k<G;k++){P0[k]=ln(U[k],m,t)+ln(S[k],s,d);if(has){const e=last-U[k];LL[k]=-.5*(L2PI+S[k])-.5*e*e*IV[k]}else LL[k]=0}}
function norm(logw){let mx=-Infinity;for(const x of logw)if(x>mx)mx=x;const w=new Float64Array(logw.length);let z=0;for(let i=0;i<w.length;i++){w[i]=Math.exp(logw[i]-mx);z+=w[i]}for(let i=0;i<w.length;i++)w[i]/=z;return w}
function sufficient(){const t0=performance.now(),l=new Float64Array(G);let map=0,mx=-Infinity;for(let k=0;k<G;k++){const u=U[k],ssr=st.sx2-2*u*st.sx+st.n*u*u,x=P0[k]-.5*st.n*(L2PI+S[k])-.5*ssr*IV[k];l[k]=x;if(x>mx){mx=x;map=k}}return{kind:'grid',weights:norm(l),map,computeMs:performance.now()-t0,exact:true,stateLabel:`${G.toLocaleString()} cells + (n, Σx, Σx²)`}}
function reference(){const t0=performance.now(),{m,t,s,d}=pars(),l=new Float64Array(G);let map=0,mx=-Infinity;for(let k=0;k<G;k++){let x=ln(U[k],m,t)+ln(S[k],s,d);for(const o of st.xs){const e=o-U[k];x+=-.5*(L2PI+S[k])-.5*e*e/V[k]}l[k]=x;if(x>mx){mx=x;map=k}}return{kind:'grid',weights:norm(l),map,computeMs:performance.now()-t0,exact:true,stateLabel:`${G.toLocaleString()} cells + full history`}}
function analytic(){const t0=performance.now(),{m,t,s,d}=pars(),tp=1/(t*t),w=new Float64Array(C.ny),mu=new Float64Array(C.ny),va=new Float64Array(C.ny),lm=new Float64Array(C.ny);let mx=-Infinity;for(let j=0;j<C.ny;j++){const k=j*C.nx,iv=IV[k],A=tp+st.n*iv,B=m*tp+st.sx*iv,D=m*m*tp+st.sx2*iv;mu[j]=B/A;va[j]=1/A;const x=ln(S[k],s,d)-.5*st.n*(L2PI+S[k])-.5*Math.log(t*t)-.5*Math.log(A)-.5*(D-B*B/A);lm[j]=x;if(x>mx)mx=x}let z=0;for(let j=0;j<C.ny;j++){w[j]=Math.exp(lm[j]-mx);z+=w[j]}for(let j=0;j<C.ny;j++)w[j]/=z;return{kind:'analytic',w,mu,va,computeMs:performance.now()-t0,exact:true,stateLabel:`${C.ny} log-v weights + closed-form u|v`}}
function gh(u,s){const {m,t,s:sm,d}=pars(),iv=Math.exp(-s),ssr=st.sx2-2*u*st.sx+st.n*u*u;return{gu:-(u-m)/(t*t)+(st.sx-st.n*u)*iv,gs:-(s-sm)/(d*d)-.5*st.n+.5*ssr*iv,a:1/(t*t)+st.n*iv,b:(st.sx-st.n*u)*iv,c:1/(d*d)+.5*ssr*iv}}
function lp(u,s){const {m,t,s:sm,d}=pars(),ssr=st.sx2-2*u*st.sx+st.n*u*u;return ln(u,m,t)+ln(s,sm,d)-.5*st.n*(L2PI+s)-.5*ssr*Math.exp(-s)}
function mode0(){const {m,s}=pars();if(!st.n)return{u:m,s};const u=st.sx/st.n,v=Math.max(Math.exp(C.s0),st.sx2/st.n-u*u);return{u:Math.max(C.u0,Math.min(C.u1,u)),s:Math.max(C.s0,Math.min(C.s1,Math.log(v)))}}
function lap(diag){const t0=performance.now();let {u,s}=mode0(),p=lp(u,s);for(let it=0;it<14;it++){const h=gh(u,s),det=h.a*h.c-h.b*h.b;if(det<=1e-12)break;const du=(h.c*h.gu-h.b*h.gs)/det,ds=(-h.b*h.gu+h.a*h.gs)/det;if(Math.hypot(du,ds)<1e-8)break;let a=1,ok=false;for(let z=0;z<12;z++){const nu=Math.max(C.u0,Math.min(C.u1,u+a*du)),ns=Math.max(C.s0,Math.min(C.s1,s+a*ds)),np=lp(nu,ns);if(np>=p){u=nu;s=ns;p=np;ok=true;break}a*=.5}if(!ok)break}const h=gh(u,s),a=h.a,b=diag?0:h.b,c=h.c,det=Math.max(1e-12,a*c-b*b);return{kind:diag?'diag':'laplace',u,s,a,b,c,uu:c/det,us:-b/det,ss:a/det,computeMs:performance.now()-t0,exact:false,stateLabel:diag?'2 means + 2 variances':'2 means + 3 covariance terms'}}
function weights(r){if(r.kind==='grid')return r.weights;const l=new Float64Array(G);if(r.kind==='analytic'){for(let j=0;j<C.ny;j++){const lw=Math.log(Math.max(r.w[j],1e-300)),m=r.mu[j],v=r.va[j],z=-.5*(L2PI+Math.log(v));for(let i=0;i<C.nx;i++){const k=j*C.nx+i,e=U[k]-m;l[k]=lw+z-.5*e*e/v}}}else for(let k=0;k<G;k++){const du=U[k]-r.u,ds=S[k]-r.s;l[k]=-.5*(r.a*du*du+2*r.b*du*ds+r.c*ds*ds)}return norm(l)}
function selected(){switch(ui.mode.value){case'reference':return reference();case'sufficient':return sufficient();case'analytic':return analytic();case'laplace':return lap(false);case'diag':return lap(true);default:return sufficient()}}
const gpdf=(x,m,v)=>{const e=x-m;return Math.exp(-.5*(L2PI+Math.log(v)+e*e/v))};
function ppdf(r,x){if(r.kind==='analytic'){let y=0;for(let j=0;j<C.ny;j++)y+=r.w[j]*gpdf(x,r.mu[j],V[j*C.nx]+r.va[j]);return y}if(r.kind==='grid'){let y=0;for(let k=0;k<G;k++)y+=r.weights[k]*gpdf(x,U[k],V[k]);return y}const vs=Math.max(1e-10,r.ss),vu=Math.max(1e-10,r.uu-r.us*r.us/vs);let y=0,z=0;for(let j=0;j<C.ny;j++){const s=S[j*C.nx],ds=s-r.s,w=Math.exp(-.5*ds*ds/vs),m=r.u+r.us/vs*ds;y+=w*gpdf(x,m,Math.exp(s)+vu);z+=w}return y/z}
function sample(r,n,superS=false){const xs=new Float64Array(n),ys=new Float64Array(n),dx=(C.x1-C.x0)/n;for(let i=0;i<n;i++){const x=C.x0+i*dx;xs[i]=x+.5*dx;ys[i]=superS?(ppdf(r,x+.2113248654*dx)+ppdf(r,x+.5*dx)+ppdf(r,x+.7886751346*dx))/3:ppdf(r,xs[i])}return{xs,ys,dx}}
function dens(s){let z=0;for(let i=0;i<s.ys.length;i++)z+=s.ys[i]*s.dx;const y=new Float64Array(s.ys.length);for(let i=0;i<y.length;i++)y[i]=s.ys[i]/z;return{xs:s.xs,ys:y,dx:s.dx}}
function dkl(a,b){let k=0,e=1e-300;for(let i=0;i<a.length;i++)if(a[i]>0)k+=a[i]*Math.log((a[i]+e)/(b[i]+e));return Math.max(0,k)}
function xkl(a,b){a=dens(a);b=dens(b);let k=0,e=1e-300;for(let i=0;i<a.ys.length;i++)if(a.ys[i]>0)k+=a.ys[i]*Math.log((a.ys[i]+e)/(b.ys[i]+e))*a.dx;return Math.max(0,k)}
class Dist{constructor(s){s=dens(s);this.x=s.xs;this.y=s.ys;this.dx=s.dx;this.c=new Float64Array(this.x.length);let z=0;for(let i=0;i<this.x.length;i++){z+=this.y[i]*this.dx;this.c[i]=z}this.c[this.c.length-1]=1}pdf(x){if(x<=this.x[0])return this.y[0];let n=this.x.length;if(x>=this.x[n-1])return this.y[n-1];const a=(x-this.x[0])/(this.x[n-1]-this.x[0])*(n-1),i=Math.floor(a),t=a-i;return this.y[i]*(1-t)+this.y[i+1]*t}cdf(x){if(x<=this.x[0])return 0;let n=this.x.length;if(x>=this.x[n-1])return 1;const a=(x-this.x[0])/(this.x[n-1]-this.x[0])*(n-1),i=Math.floor(a),t=a-i,c0=i?this.c[i-1]:0;return c0*(1-t)+this.c[i]*t}icdf(p){if(p<=0)return this.x[0];if(p>=1)return this.x[this.x.length-1];let l=0,h=this.c.length-1;while(l<h){const m=(l+h)>>1;if(this.c[m]<p)l=m+1;else h=m}if(!l)return this.x[0];const a=this.c[l-1],b=this.c[l],t=b>a?(p-a)/(b-a):0;return this.x[l-1]*(1-t)+this.x[l]*t}qdf(p){const y=this.pdf(this.icdf(p));return y>1e-12?1/y:Infinity}}
const smooth=(a,b,x)=>{if(b<=a)return x<=a?0:1;x=(Math.max(a,Math.min(b,x))-a)/(b-a);return x*x*(3-2*x)};
function nice(a,b){const m=Math.max(Math.abs(a),Math.abs(b));if(!isFinite(m))return{e:Infinity,m:1};let e=Math.floor(Math.log10(Math.max(m,1e-300))),s=10**e;a/=s;b/=s;while(a<b){for(const q of[5,1])if(Math.ceil(a/q)<b/q)return{e,m:q};e--;a*=10;b*=10}return{e,m:1}}
function fmt(t){const v=t.m*10**t.e;if(v===0)return'0';return Math.abs(v)>=1e-3&&Math.abs(v)<1e4?Number(v.toPrecision(4)).toString():v.toExponential(2)}
function ticks(d,n){const out=[];let prev=d.icdf(0);for(let i=1;i<=n;i++){const p=i/n,next=d.icdf(p);if(prev===next)continue;let {e,m}=nice(prev,next);if(!isFinite(e)){prev=next;continue}const ik=10**-e/m,t={m:Math.floor(next*ik)*m,e,p,id:d.qdf(p)*ik};if(prev<0&&next>=0){t.m=0;t.e=0;t.id=0}out.push(t);prev=next}return out}
const desc={reference:[1,'update O(G·n)','Replays every observation at every grid cell. Intentionally dumb baseline; use it when you want to feel the cost.'],sufficient:[1,'update O(G)','Stores n, Σx, Σx² instead of replaying history. Identical grid posterior, independent of history length.'],analytic:[1,'update O(S)','Integrates u analytically and stores only the 1-D log-v mixture plus Gaussian u|v conditionals.'],laplace:[0,'roughly O(1) inference','Replaces the weird posterior field with one tilted Gaussian: loses skew, tails, changing curvature and multimodality.'],diag:[0,'roughly O(1) inference','Laplace, then deletes u↔log-v covariance too. Tiny state, but it destroys the visible funnel dependence.']};
function modeInfo(){const d=desc[ui.mode.value],r=st.sel,exact=d[0],pn=exact?'QBar predictive: exact analytic u marginalization.':'QBar predictive: selected Gaussian approximation.';ui.modeInfo.innerHTML=`<span class="badge ${exact?'exact':'approx'}">${exact?'exact reformulation':'approximation'}</span><br><strong>${d[1]}</strong><br>${d[2]}<br><br><strong>representation:</strong> ${r?r.stateLabel:'—'}<br><strong>${pn}</strong>`}
function color(k,t){t=Math.pow(Math.max(0,Math.min(1,t)),.55);const lo=[23,23,23],hi=k==='prior'?[154,154,146]:k==='likelihood'?[240,161,90]:k==='error'?[232,93,135]:[93,143,255];return lo.map((x,i)=>Math.round(x+(hi[i]-x)*t))}
const exactGrid=()=>st.exactGrid||(st.exactGrid=sufficient());
function drawField(){let v,k=st.view;if(k==='selected')v=st.selW;else if(k==='reference')v=exactGrid().weights;else if(k==='prior')v=norm(P0);else if(k==='likelihood')v=st.n?norm(LL):new Float64Array(G);else{const r=exactGrid().weights,e=1e-300;v=new Float64Array(G);let mx=0;for(let i=0;i<G;i++){v[i]=Math.min(12,Math.abs(Math.log(r[i]+e)-Math.log(st.selW[i]+e)));mx=Math.max(mx,v[i])}if(mx)for(let i=0;i<G;i++)v[i]/=mx;k='error'}let mx=0;for(const x of v)mx=Math.max(mx,x);const d=img.data,iv=mx?1/mx:0;for(let i=0,p=0;i<G;i++,p+=4){const c=color(k,v[i]*iv);d[p]=c[0];d[p+1]=c[1];d[p+2]=c[2];d[p+3]=255}of.putImageData(img,0,0);const W=field.width,H=field.height,pw=W-M.l-M.r,ph=H-M.t-M.b;f.clearRect(0,0,W,H);f.imageSmoothingEnabled=true;f.drawImage(off,M.l,M.t,pw,ph);f.strokeStyle='#303030';f.fillStyle='#aaa';f.lineWidth=1;f.font='11px system-ui';for(let x=-6;x<=6;x+=2){const px=M.l+(x-C.u0)/(C.u1-C.u0)*pw;f.beginPath();f.moveTo(px,M.t);f.lineTo(px,M.t+ph);f.stroke();f.textAlign='center';f.fillText(x,px,H-12)}for(let s=-3;s<=2;s++){const py=M.t+(C.s1-s)/(C.s1-C.s0)*ph;f.beginPath();f.moveTo(M.l,py);f.lineTo(M.l+pw,py);f.stroke();f.textAlign='right';f.fillText(s,M.l-8,py+4)}f.textAlign='center';f.fillText('u',M.l+pw/2,H-1);f.save();f.translate(13,M.t+ph/2);f.rotate(-Math.PI/2);f.fillText('log v',0,0);f.restore()}
function drawQ(){const W=qbar.width,y=47,d=st.dist;q.clearRect(0,0,W,qbar.height);q.fillStyle='#78a6ff';q.font='12px monospace';q.textAlign='left';q.textBaseline='bottom';q.fillText('Posterior predictive',8,y-14);q.beginPath();q.moveTo(0,y);q.lineTo(W,y);q.strokeStyle='rgba(255,255,255,.2)';q.stroke();for(const t of ticks(d,Math.max(180,W))){const o=smooth(72,145,W/t.id);if(o*255<=2)continue;const x=t.p*(W-1);q.beginPath();q.moveTo(x,y-8);q.lineTo(x,y+8);q.strokeStyle=`rgba(120,166,255,${o})`;q.stroke();if(o>.55){q.save();q.fillStyle=`rgba(120,166,255,${o})`;q.translate(x,y+12);q.rotate(Math.PI/2);q.textAlign='left';q.textBaseline='middle';q.fillText(fmt(t),0,0);q.restore()}}for(let i=0;i<st.xs.length;i++){const x=d.cdf(st.xs[i])*(W-1);q.beginPath();q.arc(x,y,i===st.xs.length-1?4:2.5,0,TAU);q.fillStyle=i===st.xs.length-1?'#f0a15a':'rgba(240,161,90,.45)';q.fill()}}
const klfmt=x=>x==null?'…':x<5e-7?'≈ 0':x<.001?x.toExponential(2)+' nat':x.toFixed(4)+' nat';
function chrome(){ui.mu0v.textContent=(+ui.mu0.value).toFixed(1);ui.tauv.textContent=(+ui.tau.value).toFixed(2);ui.s0v.textContent=(+ui.s0.value).toFixed(1);ui.ssdv.textContent=(+ui.ssd.value).toFixed(2);ui.undo.disabled=!st.n;ui.obs.innerHTML=st.n?st.xs.map((x,i)=>`<span>${i+1}: ${x.toFixed(2)}</span>`).join(''):'<span class="empty">None yet.</span>';ui.modeMs.textContent=st.sel.computeMs.toFixed(3)+' ms';ui.refMs.textContent=st.refMs==null?'select Reference':st.refMs.toFixed(3)+' ms';ui.posteriorKl.textContent=klfmt(st.pkl);ui.predictiveKl.textContent=klfmt(st.xkl);for(const b of ui.fieldViews.querySelectorAll('button[data-view]'))b.classList.toggle('active',b.dataset.view===st.view);modeInfo()}
function compute(){common();st.exactGrid=null;st.pkl=st.xkl=null;st.refMs=null;st.exactPred=analytic();st.sel=selected();st.selW=weights(st.sel);if(ui.mode.value==='reference'){st.refMs=st.sel.computeMs;st.exactGrid=st.sel}const pr=st.sel.exact?st.exactPred:st.sel;st.dist=new Dist(sample(pr,C.qbins,true));if(st.sel.exact)st.pkl=st.xkl=0}
function diagnose(v){if(v!==st.ver)return;const g=exactGrid();if(!st.sel.exact){st.pkl=dkl(g.weights,st.selW);st.xkl=xkl(sample(st.exactPred,C.mbins),sample(st.sel,C.mbins))}chrome();if(st.view==='reference'||st.view==='error')drawField()}
function render(){st.ver++;compute();chrome();drawField();drawQ();if(st.timer)clearTimeout(st.timer);const v=st.ver;st.timer=setTimeout(()=>{st.timer=null;diagnose(v)},90)}
function add(x){x=Math.max(C.x0,Math.min(C.x1,x));st.xs.push(x);st.n++;st.sx+=x;st.sx2+=x*x;render()}
function undo(){if(!st.n)return;const x=st.xs.pop();st.n--;st.sx-=x;st.sx2-=x*x;render()}
function reset(){st.xs=[];st.n=st.sx=st.sx2=0;render()}
function point(e){if(!st.dist)return null;const r=qbar.getBoundingClientRect(),p=Math.max(.001,Math.min(.999,(e.clientX-r.left)/r.width));return{p,x:st.dist.icdf(p)}}
qbar.addEventListener('pointermove',e=>{if(e.pointerType!=='mouse')return;const a=point(e);if(a)ui.qbarHint.textContent=`p = ${a.p.toFixed(3)} → x = ${a.x.toFixed(3)} · click to observe`});
qbar.addEventListener('pointerleave',()=>ui.qbarHint.textContent='Tap/click a probability position; QBar converts it through the predictive inverse CDF into the next observation.');
qbar.addEventListener('pointerdown',e=>{const a=point(e);if(a){ui.qbarHint.textContent=`observed x = ${a.x.toFixed(3)} from p = ${a.p.toFixed(3)}`;add(a.x)}});
ui.undo.addEventListener('click',undo);ui.reset.addEventListener('click',reset);ui.mode.addEventListener('change',render);for(const x of[ui.mu0,ui.tau,ui.s0,ui.ssd])x.addEventListener('input',render);ui.fieldViews.addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(!b)return;st.view=b.dataset.view;chrome();drawField()});
render();
